function commonLabels = getCommonChannelLabels()

commonLabels = {'Fp1', 'Fp2', 'F3', 'Fz', 'F4', 'F7', 'F8', ...
                'FC3', 'FCz', 'FC4', 'FT7', 'FT8', ...
                'C3', 'Cz', 'C4', 'TP7', 'TP8', ...
                'CP3', 'CPz', 'CP4', 'P3', 'Pz', 'P4', 'O1', 'Oz', 'O2'};